language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.4
  - 2.3.0
script:
  - "bundle exec rake validate lint"
env:
  #TODO: find a way to bypass the deprecated warnings in 3.8.5
  # - PUPPET_VERSION="~> 3.8.5"
  # - PUPPET_VERSION="~> 3.8.6"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.4.1"

sudo: false
notifications:
  email:
    - gregor@waldvogel.io
