language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.4
  - 2.3.0
script:
  - "bundle exec rake validate lint"
env:
  - PUPPET_VERSION="~> 4.2"

sudo: false
notifications:
  email:
    - gregor@waldvogel.io
